# Generated by Django 3.0.6 on 2020-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Location_Where_You_Find', models.CharField(max_length=50)),
            ],
        ),
    ]
