# Generated by Django 3.0.6 on 2020-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdetail',
            name='Picture',
            field=models.ImageField(null=True, upload_to='picture/%Y/%m/%d/'),
        ),
    ]
