# Generated by Django 3.0.6 on 2020-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0002_childdetail_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdetail',
            name='Picture',
            field=models.ImageField(null=True, upload_to='Picture/%Y/%m/%d/'),
        ),
    ]
