# Generated by Django 3.0.6 on 2020-06-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_auto_20200603_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('AdharCard_Detail', models.CharField(max_length=50)),
                ('Mobile_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VolDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('AdharCard_Detail', models.CharField(max_length=50)),
                ('Mobile_No', models.IntegerField()),
                ('Picture', models.ImageField(null=True, upload_to='picture')),
                ('Reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='childdetail',
            name='Picture',
            field=models.ImageField(null=True, upload_to='picture'),
        ),
    ]
